apiVersion: "nuclio.io/v1"
kind: "Function"
metadata:
  name: yolov8-seg
  annotations:
    description: "YOLOv8 Segmentation"
    nuclio.io/project-name: "cvat"
spec:
  runtime: "python:3.9"
  handler: "main:handler"
  
  env:
    - name: LD_LIBRARY_PATH
      value: /usr/local/lib/python3.9/dist-packages/torch/lib
  triggers:
    myHttpTrigger:
      kind: "http"
      maxWorkers: 2
  volumes:
    - volume:
        name: model
        hostPath:
          # 注意: 这里的路径是相对于你运行 nuctl 的目录
          path: "./best.pt"
      volumeMount:
        name: model
        mountPath: "/opt/nuclio/best.pt"
  resources:
    limits:
      # 如果需要 GPU 支持, 取消下面这行的注释
      # nvidia.com/gpu: 1
