FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive NVIDIA_VISIBLE_DEVICES=all

ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY}

RUN sed -i "s@http://ports.ubuntu.com@http://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl git python3 python3-pip ffmpeg libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/nuclio/sam2

RUN pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple \
    torch torchvision torchaudio pycocotools matplotlib onnxruntime onnx

RUN pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple \
    git+https://github.com/facebookresearch/sam2.git@c2ec8e14a185632b0a5d8b161928ceb50197eddc

RUN curl -L -O https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt

# Pre-install nuclio dependencies AND download whl files for nuclio onbuild
RUN pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple \
    nuclio-sdk msgpack && \
    mkdir -p /opt/nuclio/whl && \
    pip3 download -i https://pypi.tuna.tsinghua.edu.cn/simple \
    -d /opt/nuclio/whl nuclio-sdk msgpack

RUN ln -s /usr/bin/pip3 /usr/local/bin/pip && \
    ln -s /usr/bin/python3 /usr/bin/python

ENV PYTHONPATH=/opt/nuclio/sam2
